# Generated by Django 3.1.3 on 2020-11-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201126_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contents',
            name='contents_text',
            field=models.CharField(max_length=50000),
        ),
    ]
